MT5_SERVER_URL = "http://192.168.1.213:5000"
MT5_MAX_CONCURRENT_REQUESTS = 4

TRADING_PAIRS = [
    "EUR/USD",
    "EUR/JPY",
    "EUR/CAD",
    "EUR/GBP",
    "EUR/AUD",
    "EUR/CHF",
    "USD/JPY",
    "USD/CHF",
    "USD/CAD",
    "AUD/CAD",
    "AUD/USD",
    "AUD/CHF",
    "AUD/JPY",
    "GBP/USD",
    "GBP/CAD",
    "GBP/JPY",
    "GBP/AUD",
    "GBP/CHF",
    "CAD/JPY",
    "CAD/CHF",
    "CHF/JPY",
]

TIMEFRAME = "30m"
POLL_INTERVAL_SECONDS = 60
RISK_PER_TRADE_PERCENT = 1.0
USE_KRAYA_FILTER = False
